// Browser-safe UI copy: do not import the server-side Chinese filesystem converter.
const copies={
 zh:{image:'图片',detailTitle:'展开详情',title:'文章',intro:'记录、观点与研究。登录后可投稿或提出修改，由站长审核发布。',submit:'投稿与我的文章',searchLabel:'搜索文章、作者',category:'分类',all:'全部分类',search:'搜索',clear:'清除',loading:'正在读取文章…',more:'继续显示 24 篇',read:'阅读文章 ↗',edit:'提交修改 ↗',toc:'目录',related:'关联词条',unavailable:'文章服务暂不可用',missing:'缺少文章 ID',fallback:'当前显示中文原文',relatedError:'关联词条暂时无法读取。',empty:'暂无已公开文章。',shown:'已显示 {n} 篇文章',categories:{archival:'史料与考据',profile:'人物专访',business:'商业与组织','art-philosophy':'艺术与观点',infrastructure:'技术与基础设施'}},
 ja:{image:'画像',detailTitle:'詳細を表示',title:'記事',intro:'記録・視点・研究。ログインして投稿や修正を提案できます。管理者の審査後に公開されます。',submit:'投稿・自分の記事',searchLabel:'記事・著者を検索',category:'分類',all:'すべての分類',search:'検索',clear:'クリア',loading:'記事を読み込み中…',more:'さらに24件表示',read:'記事を読む ↗',edit:'修正を提案 ↗',toc:'目次',related:'関連項目',unavailable:'記事を読み込めません',missing:'記事IDがありません',fallback:'中国語の原文を表示しています',relatedError:'関連項目を読み込めません。',empty:'公開された記事はまだありません。',shown:'{n}件の記事を表示',categories:{archival:'史料・考証',profile:'人物インタビュー',business:'ビジネス・組織','art-philosophy':'芸術・視点',infrastructure:'技術・インフラ'}},
 en:{image:'Image',detailTitle:'Details',title:'Articles',intro:'Records, perspectives and research. Sign in to submit an article or propose edits for review by the site owner.',submit:'Write / my articles',searchLabel:'Search articles and authors',category:'Category',all:'All categories',search:'Search',clear:'Clear',loading:'Loading articles…',more:'Show 24 more',read:'Read article ↗',edit:'Propose an edit ↗',toc:'Contents',related:'Related entries',unavailable:'Article service unavailable',missing:'Missing article ID',fallback:'Showing the Chinese original',relatedError:'Related entries are unavailable.',empty:'No published articles yet.',shown:'Showing {n} articles',categories:{archival:'Archives and research',profile:'Profiles and interviews',business:'Business and organizations','art-philosophy':'Art and perspectives',infrastructure:'Technology and infrastructure'}}
};
export const articleCopy=locale=>copies[locale]||copies[locale?.startsWith('zh')?'zh':'en'];

const traditional={...copies.zh,title:'文章',intro:'記錄、觀點與研究。登入後可投稿或提出修改，由站長審核發布。',submit:'投稿與我的文章',searchLabel:'搜尋文章、作者',all:'全部分類',search:'搜尋',clear:'清除',loading:'正在讀取文章…',more:'繼續顯示 24 篇',read:'閱讀文章 ↗',edit:'提交修改 ↗',toc:'目錄',related:'關聯詞條',unavailable:'文章服務暫不可用',missing:'缺少文章 ID',fallback:'目前顯示中文原文',relatedError:'關聯詞條暫時無法讀取。',empty:'暫無已公開文章。',shown:'已顯示 {n} 篇文章',image:'圖片',detailTitle:'展開詳情',categories:{archival:'史料與考據',profile:'人物專訪',business:'商業與組織','art-philosophy':'藝術與觀點',infrastructure:'技術與基礎設施'}};
copies['zh-tw']=traditional;copies['zh-hk']=traditional;
Object.assign(copies.zh,{origin:'来源',allOrigins:'全部来源',origins:{'site-original':'站点原创','user-submission':'用户投稿'},writeRelated:'撰写相关文章',allRelated:'查看全部相关文章',relatedArticles:'相关文章',removeRelated:'移除词条筛选',pickRelated:'关联词条（选填）',findRelated:'搜索名称、别名或 ID',remove:'移除',retry:'重试',noMatches:'没有匹配的词条',invalidRelated:'关联词条已失效，请移除后重试',limitRelated:'最多关联 50 个词条',login:'登录后保存或投稿',intro:'站点原创与用户投稿。登录后可投稿或修改自己的文章，由维护者审核发布。'});
Object.assign(copies.ja,{origin:'出典',allOrigins:'すべての出典',origins:{'site-original':'サイトオリジナル','user-submission':'ユーザー投稿'},writeRelated:'関連記事を書く',allRelated:'すべての関連記事',relatedArticles:'関連記事',removeRelated:'項目フィルターを解除',pickRelated:'関連項目（任意）',findRelated:'名前・別名・IDで検索',remove:'削除',retry:'再試行',noMatches:'該当する項目はありません',invalidRelated:'無効な関連項目を削除してください',limitRelated:'最大50項目まで',login:'ログインして保存・投稿',intro:'サイトオリジナルとユーザー投稿。自分の記事を編集し、審査後に公開できます。'});
Object.assign(copies.en,{origin:'Source',allOrigins:'All sources',origins:{'site-original':'Site original','user-submission':'User submission'},writeRelated:'Write a related article',allRelated:'All related articles',relatedArticles:'Related articles',removeRelated:'Remove entry filter',pickRelated:'Related entries (optional)',findRelated:'Search names, aliases or IDs',remove:'Remove',retry:'Retry',noMatches:'No matching entries',invalidRelated:'Remove unavailable related entries before submitting',limitRelated:'Up to 50 related entries',login:'Sign in to save or submit',intro:'Site originals and user submissions. Sign in to submit or edit your own articles for review.'});
Object.assign(traditional,{origin:'來源',allOrigins:'全部來源',origins:{'site-original':'站點原創','user-submission':'用戶投稿'},writeRelated:'撰寫相關文章',allRelated:'查看全部相關文章',relatedArticles:'相關文章',removeRelated:'移除詞條篩選',pickRelated:'關聯詞條（選填）',findRelated:'搜尋名稱、別名或 ID',remove:'移除',retry:'重試',noMatches:'沒有符合的詞條',invalidRelated:'關聯詞條已失效，請移除後重試',limitRelated:'最多關聯 50 個詞條',login:'登入後儲存或投稿',intro:'站點原創與用戶投稿。登入後可投稿或修改自己的文章，由維護者審核發布。'});

for(const [locale,values] of Object.entries({zh:{editorHint:'正文会自动保存在本机。登录后可保存云端草稿，并提交审核。',serverSaved:'草稿已保存到云端。'},en:{editorHint:'Your writing is saved on this device. Sign in to save a cloud draft and submit for review.',serverSaved:'Draft saved to your account.'},ja:{editorHint:'本文はこの端末に自動保存されます。ログインするとクラウド保存・審査への提出ができます。',serverSaved:'下書きをクラウドに保存しました。'},'zh-tw':{editorHint:'正文會自動儲存在本機。登入後可儲存雲端草稿，並提交審核。',serverSaved:'草稿已儲存至雲端。'},'zh-hk':{editorHint:'正文會自動儲存在本機。登入後可儲存雲端草稿，並提交審核。',serverSaved:'草稿已儲存至雲端。'}}))Object.assign(copies[locale],values);

const conflicts={
 zh:{title:'云端草稿已更新',detail:'当前编辑内容仍在本机。请比较两个版本再继续。',untitled:'未命名草稿',local:'本机版本',cloud:'云端版本',fork:'保留当前内容，另存新草稿',load:'备份当前内容并载入云端',backupFailed:'本机备份失败；请先复制正文后再载入云端。',restore:'恢复冲突前的本机版本',restored:'已恢复本机版本；云端版本未改变。',loaded:'已载入云端版本；原本地内容已备份，可随时恢复。'},
 'zh-tw':{title:'雲端草稿已更新',detail:'目前編輯內容仍在本機。請比較兩個版本後再繼續。',untitled:'未命名草稿',local:'本機版本',cloud:'雲端版本',fork:'保留目前內容，另存新草稿',load:'備份目前內容並載入雲端',backupFailed:'本機備份失敗；請先複製正文後再載入雲端。',restore:'還原衝突前的本機版本',restored:'已還原本機版本；雲端版本未變更。',loaded:'已載入雲端版本；原本機內容已備份，可隨時還原。'},
 'zh-hk':{title:'雲端草稿已更新',detail:'目前編輯內容仍在本機。請比較兩個版本後再繼續。',untitled:'未命名草稿',local:'本機版本',cloud:'雲端版本',fork:'保留目前內容，另存新草稿',load:'備份目前內容並載入雲端',backupFailed:'本機備份失敗；請先複製正文後再載入雲端。',restore:'還原衝突前的本機版本',restored:'已還原本機版本；雲端版本未變更。',loaded:'已載入雲端版本；原本機內容已備份，可隨時還原。'},
 ja:{title:'クラウドの下書きが更新されました',detail:'編集中の内容はこの端末に残っています。両方の版を確認してから続行してください。',untitled:'無題の下書き',local:'この端末の版',cloud:'クラウドの版',fork:'現在の内容を新しい下書きとして保存',load:'現在の内容を控えてクラウド版を読み込む',backupFailed:'端末への控えの保存に失敗しました。本文をコピーしてから読み込んでください。',restore:'衝突前の端末版に戻す',restored:'端末版に戻しました。クラウド版は変更していません。',loaded:'クラウド版を読み込みました。元の端末版は保存済みで、復元できます。'},
 en:{title:'Cloud draft changed',detail:'Your current edits remain on this device. Compare both versions before continuing.',untitled:'Untitled draft',local:'Device version',cloud:'Cloud version',fork:'Save current edits as a new draft',load:'Back up current edits and load cloud version',backupFailed:'Could not back up your edits on this device. Copy the body before loading the cloud version.',restore:'Restore the device version',restored:'Device version restored. The cloud version was not changed.',loaded:'Cloud version loaded. Your earlier device version is backed up and can be restored.'}
};
for(const locale of Object.keys(conflicts))copies[locale].conflict=conflicts[locale];

const recoveries={
 zh:{authUnavailable:'暂时无法确认当前账号。正文已保存在本机，请恢复连接后再保存云端。',guest:'导入登录前草稿',unverified:'导入账号未确认时的草稿',legacy:'导入旧版本地草稿',ownerMismatch:'草稿归属与当前账号不符。',replace:'导入将替换当前编辑区，是否继续？',invalid:'草稿无法恢复。'},
 'zh-tw':{authUnavailable:'暫時無法確認目前帳號。正文已儲存在本機，請恢復連線後再儲存至雲端。',guest:'匯入登入前草稿',unverified:'匯入帳號未確認時的草稿',legacy:'匯入舊版本機草稿',ownerMismatch:'草稿歸屬與目前帳號不符。',replace:'匯入將取代目前編輯區，是否繼續？',invalid:'草稿無法還原。'},
 'zh-hk':{authUnavailable:'暫時無法確認目前帳號。正文已儲存在本機，請恢復連線後再儲存至雲端。',guest:'匯入登入前草稿',unverified:'匯入帳號未確認時的草稿',legacy:'匯入舊版本機草稿',ownerMismatch:'草稿歸屬與目前帳號不符。',replace:'匯入將取代目前編輯區，是否繼續？',invalid:'草稿無法還原。'},
 ja:{authUnavailable:'現在のアカウントを確認できません。本文はこの端末に保存されています。接続が戻ってからクラウドに保存してください。',guest:'ログイン前の下書きを読み込む',unverified:'アカウント未確認時の下書きを読み込む',legacy:'旧版の端末下書きを読み込む',ownerMismatch:'この下書きは現在のアカウントのものではありません。',replace:'読み込むと現在の編集内容が置き換わります。続行しますか？',invalid:'下書きを復元できません。'},
 en:{authUnavailable:'Your account cannot be confirmed right now. Your writing is saved on this device; save to the cloud after reconnecting.',guest:'Import pre-login draft',unverified:'Import draft saved while account was unverified',legacy:'Import older device draft',ownerMismatch:'This draft belongs to a different account.',replace:'Importing will replace your current edits. Continue?',invalid:'Could not restore this draft.'}
};
for(const locale of Object.keys(recoveries))copies[locale].recovery=recoveries[locale];
