import {resolveLocaleCopy} from './i18n.mjs';
export const creatorCenterCopy=locale=>{
 const base=resolveLocaleCopy({
 zh:{title:'创作者中心',intro:'处理审核意见，继续草稿，管理每一份投稿。',back:'我的空间',create:'新建投稿',entry:'词条',article:'文章',gallery:'图库',setCountUnit:'套设定',attention:'需要处理',review:'审核中',published:'已公开',draft:'云端草稿',local:'本机草稿',localNote:'只在此浏览器保存，尚未提交审核。',todo:'接下来要处理',todoEmpty:'目前没有需要处理的投稿。',dashboard:'贡献进度',recent:'最近投稿',records:'全部投稿',search:'搜索投稿标题',type:'类型',state:'状态',all:'全部',updated:'最近更新',action:'下一步',open:'查看详情',reviewProgress:'查看审核进度',continue:'继续编辑',deleteDraft:'删除草稿',deleteDraftPrompt:'永久删除「{title}」？这份未提交的草稿将无法恢复。',deleteGalleryDraftPrompt:'永久删除「{title}」？这份未提交的草稿及其私有暂存图片将无法恢复。',cancel:'取消',deleted:'草稿已删除。',untitled:'未命名草稿',revise:'修改后重投',viewPublic:'查看公开内容',newEntry:'编辑词条',newArticle:'投稿文章',newGallery:'投稿图片',photoRecord:'照片',classificationRecord:'分类建议',photoCountUnit:'张',photoCountPlural:'张',loading:'正在读取投稿…',empty:'没有符合条件的投稿。',error:'暂时无法读取，请重试。',retry:'重试',previous:'上一页',next:'下一页',close:'返回列表',notifications:'审核提醒',unread:'未读',noNotifications:'暂时没有审核提醒。',login:'登录后查看投稿',signIn:'登录账号',loginHint:'登录后在这里查看投稿、审核意见和进度。',feedback:'审核意见',noFeedback:'还没有审核意见。',images:'图片审核',recordId:'记录编号',syncing:'正在同步 GitHub',partial:'部分图片已公开',status:{attention:'需要处理',review:'审核中',published:'已公开',draft:'草稿'},phase:{draft:'云端草稿',pending_review:'待审核',changes_requested:'需要修改',approved_syncing:'审核通过 · 等待公开',partially_public:'部分公开',published:'已公开',hidden:'已下架'},imageStatus:{pending:'待审核',approved:'审核通过',rejected:'已退回'},events:{returned:'审核退回',reviewed:'审核已有结果',published:'内容已公开',comment:'收到新意见','sync-failed':'同步需要处理'}},
 en:{title:'Creator center',intro:'Resolve feedback, resume drafts, and manage your contributions.',back:'My space',create:'New contribution',entry:'Entry',article:'Article',gallery:'Gallery',setCountUnit:'sets',attention:'Needs action',review:'In review',published:'Published',draft:'Cloud drafts',local:'Local drafts',localNote:'Saved only in this browser; not submitted for review.',todo:'Next to handle',todoEmpty:'Nothing needs your attention right now.',dashboard:'Contribution progress',recent:'Recent contributions',records:'All contributions',search:'Search titles',type:'Type',state:'Status',all:'All',updated:'Updated',action:'Next step',open:'View details',reviewProgress:'View review progress',continue:'Continue editing',deleteDraft:'Delete draft',deleteDraftPrompt:'Permanently delete “{title}”? This unsubmitted draft cannot be restored.',deleteGalleryDraftPrompt:'Permanently delete “{title}”? This unsubmitted draft and its private staged images cannot be restored.',cancel:'Cancel',deleted:'Draft deleted.',untitled:'Untitled draft',revise:'Revise and resubmit',viewPublic:'View published content',newEntry:'Edit an entry',newArticle:'Write an article',newGallery:'Contribute images',photoRecord:'Photo',classificationRecord:'Classification suggestion',photoCountUnit:'photo',photoCountPlural:'photos',loading:'Loading contributions…',empty:'No matching contributions.',error:'Unable to load. Please retry.',retry:'Retry',previous:'Previous',next:'Next',close:'Back to list',notifications:'Review updates',unread:'Unread',noNotifications:'No review updates yet.',login:'Sign in to view contributions',signIn:'Sign in',loginHint:'Sign in to see your submissions, reviews and progress here.',feedback:'Review feedback',noFeedback:'No review feedback yet.',images:'Image review',recordId:'Record ID',syncing:'Syncing to GitHub',partial:'Some images published',status:{attention:'Needs action',review:'In review',published:'Published',draft:'Draft'},phase:{draft:'Cloud draft',pending_review:'Pending review',changes_requested:'Changes requested',approved_syncing:'Approved · awaiting publication',partially_public:'Partially published',published:'Published',hidden:'Unpublished'},imageStatus:{pending:'Pending',approved:'Approved',rejected:'Returned'},events:{returned:'Returned for changes',reviewed:'Review updated',published:'Published',comment:'New feedback','sync-failed':'Sync needs attention'}},
 ja:{title:'クリエイターセンター',intro:'審査の意見に対応し、下書きを続け、投稿を管理します。',back:'マイスペース',create:'新規投稿',entry:'項目',article:'記事',gallery:'ギャラリー',setCountUnit:'件の設定',attention:'対応が必要',review:'審査中',published:'公開済み',draft:'クラウド下書き',local:'端末の下書き',localNote:'このブラウザーにのみ保存。審査には未提出です。',todo:'次に対応すること',todoEmpty:'対応が必要な投稿はありません。',dashboard:'投稿の進捗',recent:'最近の投稿',records:'すべての投稿',search:'タイトルで検索',type:'種類',state:'状態',all:'すべて',updated:'更新日時',action:'次の操作',open:'詳細を見る',reviewProgress:'審査の進捗を見る',continue:'編集を続ける',deleteDraft:'下書きを削除',deleteDraftPrompt:'「{title}」を完全に削除しますか？未提出の下書きは復元できません。',deleteGalleryDraftPrompt:'「{title}」を完全に削除しますか？未提出の下書きと非公開の一時画像は復元できません。',cancel:'キャンセル',deleted:'下書きを削除しました。',untitled:'無題の下書き',revise:'修正して再提出',viewPublic:'公開ページを見る',newEntry:'項目を編集',newArticle:'記事を投稿',newGallery:'画像を投稿',photoRecord:'画像',classificationRecord:'分類案',photoCountUnit:'枚',photoCountPlural:'枚',loading:'投稿を読み込み中…',empty:'該当する投稿はありません。',error:'読み込めません。再試行してください。',retry:'再試行',previous:'前へ',next:'次へ',close:'一覧に戻る',notifications:'審査のお知らせ',unread:'未読',noNotifications:'審査のお知らせはありません。',login:'ログインして投稿を見る',signIn:'ログイン',loginHint:'ログインすると投稿・審査結果・進捗をここで確認できます。',feedback:'審査の意見',noFeedback:'審査の意見はまだありません。',images:'画像の審査',recordId:'記録 ID',syncing:'GitHub に同期中',partial:'一部の画像を承認',status:{attention:'対応が必要',review:'審査中',published:'公開済み',draft:'下書き'},phase:{draft:'クラウド下書き',pending_review:'審査待ち',changes_requested:'修正が必要',approved_syncing:'承認済み・公開待ち',partially_public:'一部公開',published:'公開済み',hidden:'非公開'},imageStatus:{pending:'審査待ち',approved:'承認済み',rejected:'差し戻し'},events:{returned:'修正依頼',reviewed:'審査結果',published:'公開済み',comment:'新しい意見','sync-failed':'同期への対応が必要'}}
 },locale);
 const timeline=resolveLocaleCopy({zh:{timeline:'时间轴',newTimeline:'投稿事件',guestStart:'从一个明确的投稿任务开始',guestGuide:'阅读投稿指南'},ja:{timeline:'年表',newTimeline:'出来事を投稿',guestStart:'投稿する内容を選びましょう',guestGuide:'投稿ガイドを読む'},en:{timeline:'Timeline',newTimeline:'Submit an event',guestStart:'Choose what you want to contribute',guestGuide:'Read the contribution guide'}},locale);
 const controls=resolveLocaleCopy({
  zh:{withdrawn:'已撤回',withdraw:'撤回投稿',withdrawPrompt:'撤回「{title}」？尚未通过的部分会退出审核；已公开内容仍会保留。',withdrawPending:'正在撤回投稿…',withdrawSuccess:'撤回请求已提交；审核队列和投稿状态正在更新。',deleteSubmission:'永久删除投稿',deleteSubmissionPrompt:'永久删除「{title}」？审核记录和私有暂存图片将无法恢复。',deletingDraft:'正在删除草稿…',deletingSubmission:'正在删除投稿…',deletedSubmission:'投稿已永久删除。',viewFeedback:'查看审核意见',deleteUnavailable:'已有通过或公开内容，不能删除整份投稿。'},
  ja:{withdrawn:'取り下げ済み',withdraw:'投稿を取り下げる',withdrawPrompt:'「{title}」を取り下げますか？未承認の内容は審査から外れ、公開済みの内容は残ります。',withdrawPending:'投稿を取り下げています…',withdrawSuccess:'取り下げを受け付けました。審査状況を更新しています。',deleteSubmission:'投稿を完全に削除',deleteSubmissionPrompt:'「{title}」を完全に削除しますか？審査履歴と非公開画像は復元できません。',deletingDraft:'下書きを削除しています…',deletingSubmission:'投稿を削除しています…',deletedSubmission:'投稿を完全に削除しました。',viewFeedback:'審査の意見を見る',deleteUnavailable:'承認済みまたは公開済みの内容があるため、投稿全体は削除できません。'},
  en:{withdrawn:'Withdrawn',withdraw:'Withdraw submission',withdrawPrompt:'Withdraw “{title}”? Unapproved work leaves review; published content stays visible.',withdrawPending:'Withdrawing submission…',withdrawSuccess:'Withdrawal requested. Review and contribution status are updating.',deleteSubmission:'Permanently delete submission',deleteSubmissionPrompt:'Permanently delete “{title}”? Review history and private staged photos cannot be recovered.',deletingDraft:'Deleting draft…',deletingSubmission:'Deleting submission…',deletedSubmission:'Submission permanently deleted.',viewFeedback:'Read review feedback',deleteUnavailable:'This submission includes approved or published content and cannot be deleted as a whole.'}
 },locale);
 const localGallery=resolveLocaleCopy({
  zh:{deleteLocalCopy:'移除本机副本',deleteLocalGalleryPrompt:'移除「{title}」的本机副本？尚未私有暂存的本机图片将无法恢复，云端草稿仍保留。',localGalleryDeleted:'本机草稿已移除。',localNote:'此处显示本机保存的编辑副本；云端状态以投稿记录为准。'},
  ja:{deleteLocalCopy:'端末内のコピーを削除',deleteLocalGalleryPrompt:'「{title}」の端末内コピーを削除しますか？非公開で一時保存していない画像は復元できません。クラウドの下書きは残ります。',localGalleryDeleted:'端末内の下書きを削除しました。',localNote:'このブラウザーの編集用コピーです。クラウド上の状態は投稿記録で確認してください。'},
  en:{deleteLocalCopy:'Remove local copy',deleteLocalGalleryPrompt:'Remove the local copy of “{title}”? Photos not privately staged cannot be restored. The cloud draft remains.',localGalleryDeleted:'Local draft removed.',localNote:'Editing copies saved in this browser. Check contribution records for cloud status.'}
 },locale);
 return {...base,...timeline,...controls,...localGallery,phase:{...base.phase,withdrawn:controls.withdrawn},status:{...base.status,withdrawn:controls.withdrawn},imageStatus:{...base.imageStatus,withdrawn:controls.withdrawn}};
};
