import {resolveLocaleCopy} from './i18n.mjs';
export function mountGalleryDraftStatus(root,locale,controller){
 const c=resolveLocaleCopy({zh:{local:'本机',cloud:'云端',saved:'已保存',saving:'正在保存',pending:'等待同步',localOnly:'仅本机',offline:'离线，恢复连接后继续同步',error:'本机保存失败，请保留此页',login:'登录已失效，内容仍在本机',conflict:'另一窗口或设备更新了此草稿。两份内容均保留，请选择继续使用哪一份。',keep:'使用本机内容继续同步',remote:'载入云端内容',retry:'重试云端同步'},ja:{local:'端末',cloud:'クラウド',saved:'保存済み',saving:'保存中',pending:'同期待ち',localOnly:'端末のみ',offline:'オフライン。再接続後に同期します',error:'端末への保存に失敗しました。ページを閉じないでください',login:'再ログインが必要です。内容は端末に保持されています',conflict:'他の画面で更新されています。両方の内容を保持しています。',keep:'端末の内容を使用',remote:'クラウドの内容を開く',retry:'同期を再試行'},en:{local:'Device',cloud:'Cloud',saved:'Saved',saving:'Saving',pending:'Waiting to sync',localOnly:'Device only',offline:'Offline; sync resumes after reconnecting',error:'Device save failed. Keep this page open',login:'Sign in again; content remains on this device',conflict:'Another window or device updated this draft. Both copies are retained. Choose which to continue with.',keep:'Keep device content',remote:'Load cloud content',retry:'Retry cloud sync'}},locale);
 let local=root.querySelector('[data-draft-local-state]'),cloud=root.querySelector('[data-draft-cloud-state]');
 if(!local||!cloud){const status=document.createElement('div');status.className='gallery-draft-status';status.setAttribute('role','status');status.setAttribute('aria-live','polite');local=document.createElement('span');local.dataset.draftLocalState='';cloud=document.createElement('span');cloud.dataset.draftCloudState='';status.append(local,document.createTextNode(' · '),cloud);root.prepend(status);}
 let conflict=root.querySelector('[data-draft-conflict]');
 if(!conflict){conflict=document.createElement('div');conflict.dataset.draftConflict='';conflict.hidden=true;const note=document.createElement('p');note.textContent=c.conflict;conflict.append(note);for(const [name,label]of [['local',c.keep],['remote',c.remote]]){const button=document.createElement('button');button.type='button';button.dataset[name==='local'?'draftUseLocal':'draftUseRemote']='';button.textContent=label;conflict.append(button);}root.prepend(conflict);}
 for(const choice of ['local','remote'])root.querySelector(`[data-draft-use-${choice}]`)?.addEventListener('click',async()=>{const buttons=[...conflict.querySelectorAll('button')];buttons.forEach(button=>button.disabled=true);try{await controller().resolve(choice);}catch{}finally{buttons.forEach(button=>button.disabled=false);}});
 const retry=document.createElement('button');retry.type='button';retry.textContent=c.retry;retry.hidden=true;retry.onclick=()=>void controller().sync().catch(()=>{});cloud.after(retry);
 return state=>{local.textContent=`${c.local}：${c[state.local]||state.local}`;cloud.textContent=`${c.cloud}：${c[state.cloud==='local'?'localOnly':state.cloud]||state.cloud}${state.error&&state.cloud==='offline'?' · '+state.error.message:''}`;conflict.hidden=!state.conflict;retry.hidden=!['offline','login'].includes(state.cloud);};
}
