import {createArticleAutosave} from '../lib/articleAutosave.mjs';
import {articleCreationCopy} from '../lib/articleCreationCopy.mjs';
const confirmEditorPopover=async(_root,message)=>window.confirm(message);
const openEditorPopover=(_root,dialog)=>dialog.showModal();
import {articleCopy} from '../lib/articleCopy.mjs';
import {createContextAction} from '../lib/contextAction.js';
import {withLockedEditorWorkspace} from '../lib/editorWorkingState.mjs';
import {showContributionReceipt} from '../lib/submissionReceipt.mjs';
// Persistence adapter for the shared encyclopedia workbench. Editing stays in visualEditor.js.
export function initializeArticleSubmission(root,editor,ownerId='guest',{confirm=confirmEditorPopover}={}){
 const $=selector=>root.querySelector(selector),status=$('[data-article-status]');
 const admin=new URL(location.href).searchParams.get('admin')==='1',locale=root.dataset.contentLocale,requestedId=new URL(location.href).searchParams.get('id'),requestedRevision=new URL(location.href).searchParams.get('revision');
 if(admin){
  $('[data-article-submit]').textContent=locale==='en'?'Publish article':locale==='ja'?'記事を公開':'发布文章';
  const back=root.querySelector('.ve-home');
  if(back){back.href=root.dataset.articleApi+'/admin/content?type=article';back.textContent='← '+(locale==='en'?'Content management':locale==='ja'?'コンテンツ管理':'内容管理');}
 }
 const editorCopy=JSON.parse($('[data-editor-copy]').textContent);
 const confirmReplace=()=>confirm(root,editorCopy.replace,{accept:editorCopy.apply,cancel:editorCopy.cancel});
 const key=`article-submission-v2:${ownerId}:${admin?'admin:':''}${locale}:${new URL(location.href).searchParams.get('draft')||requestedRevision||requestedId||'new'}`;
 let state={},busy=false,offset=0,next=null,needsRestore=false,ready=false,casConflict=false;
 try{state=JSON.parse(localStorage.getItem(key)||'{}');}catch{}
 state.operationId ||= crypto.randomUUID();
 const persist=()=>{try{localStorage.setItem(key,JSON.stringify(state));}catch{/* Cloud saves remain valid when browser storage is unavailable. */}$('[data-locale-select]').disabled=Boolean(state.articleId);};
 $('[data-locale-select]').disabled=Boolean(state.articleId);
 const cloudCopy=articleCreationCopy(root.dataset.locale||locale),cloudStatus=$('[data-article-cloud-status]');
 const copy=articleCopy(root.dataset.locale || locale);const say=text=>{status.textContent=text;};
 const flowText=({zh:{pending:'已提交审核。维护者批准前，公开正文不会改变。'},ja:{pending:'審査に提出しました。承認まで公開本文は変わりません。'},en:{pending:'Submitted for review. The public article will not change until approved.'}})[locale]||({zh:{pending:'已提交审核。维护者批准前，公开正文不会改变。'}}).zh;
 const receipt=()=>showContributionReceipt(root,{id:state.revisionId,state:admin?'文章已公开。可从内容管理查看修订记录。':flowText.pending,href:admin?root.dataset.articleApi+'/admin/content?type=article':`/${root.dataset.locale}/account/creator/?recordType=article&record=${encodeURIComponent(state.revisionId)}`,...(admin?{title:'发布完成',recordLabel:'修订编号',linkLabel:'查看内容管理'}:{})});
 const call=async(path,method='GET',body)=>{if(editor.currentOwner&&editor.currentOwner()!==ownerId)throw Error('账号已变化，请重新打开此页面。');const res=await fetch(root.dataset.articleApi+'/api/'+(admin?'admin/':'')+'articles'+path,{method,credentials:'include',signal:AbortSignal.timeout(15000),headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await res.json();if(editor.currentOwner&&editor.currentOwner()!==ownerId)throw Error('账号已变化，请重新打开此页面。');if(!res.ok){const error=Error(data.error?.message||'文章服务暂不可用');error.status=res.status;error.code=data.error?.code;error.server=data.error?.server;throw error;}return data;};
 const showSaveConflict=server=>{
  casConflict=true;
  let panel=$('[data-article-save-conflict]');
  if(!panel){panel=document.createElement('section');panel.dataset.articleSaveConflict='';panel.className='ve-article-save-conflict';status.after(panel);}
  panel.replaceChildren();
  const local=editor.snapshot(),message=copy.conflict,heading=document.createElement('h3');
  heading.textContent=message.title;
  const detail=document.createElement('p');detail.textContent=message.detail;
  const version=(label,content)=>{const box=document.createElement('details'),summary=document.createElement('summary'),body=document.createElement('pre');summary.textContent=`${label} · ${content?.title||message.untitled}`;body.textContent=content?.body||'';box.append(summary,body);return box;};
  panel.append(heading,detail,version(message.local,local.content),version(message.cloud,server?.content));
  const fork=document.createElement('button');fork.type='button';fork.textContent=message.fork;
  fork.onclick=()=>run(async()=>{state.revisionId=null;state.fingerprint=null;state.draftVersion=null;state.operationId=crypto.randomUUID();persist();casConflict=false;auto.resume();await auto.flush();panel.remove();});
  const load=document.createElement('button');load.type='button';load.textContent=message.load;load.disabled=!server?.content;
  load.onclick=()=>{try{localStorage.setItem(`${key}:conflict:${Date.now()}`,JSON.stringify(local));}catch{say(message.backupFailed);return;}editor.restore(server.content,state.locale||locale);state.fingerprint=server.fingerprint;state.draftVersion=server.draftVersion;persist();casConflict=false;auto.accept();panel.replaceChildren();const restore=document.createElement('button');restore.type='button';restore.textContent=message.restore;restore.onclick=()=>{editor.restore(local.content,state.locale||locale);auto.resume();panel.remove();say(message.restored);};panel.append(restore);say(message.loaded);};
  panel.append(fork,load);
 };
 const run=async(action)=>{if(busy)return;busy=true;root.setAttribute('aria-busy','true');const controls=[...root.querySelectorAll('[data-article-save],[data-article-submit],[data-article-new],[data-article-mine],[data-article-prev],[data-article-next]')];controls.forEach(button=>button.disabled=true);try{await withLockedEditorWorkspace(root,action,{allowDialogs:true});}catch(error){say(error.message);if(error.code==='draft_conflict')showSaveConflict(error.server);if(error.status===401){const a=createContextAction(copy.login,`/${root.dataset.locale}/account/?returnTo=${encodeURIComponent(location.pathname+location.search)}`);a.addEventListener('click',()=>editor.prepareNavigation?.());status.append(' ',a);}}finally{busy=false;root.removeAttribute('aria-busy');controls.forEach(button=>button.disabled=false);}};
 const save=async(draft=editor.snapshot())=>{if(ownerId==='unverified')throw Error(copy.recovery.authUnavailable);if(needsRestore)throw Error('请先从我的提案载入服务端草稿，或明确新建文章。');if(state.submitted)throw Error('这份提案已经提交。请从我的提案查看状态，或新建文章。');state.operationId ||= crypto.randomUUID();persist();const result=await call('/drafts?locale='+(state.locale||draft.locale),'POST',{revisionId:state.revisionId,operationId:state.operationId,expectedVersion:state.draftVersion??undefined,expectedFingerprint:state.fingerprint,articleId:state.articleId,baseVersion:state.baseVersion,content:draft.content,...(admin?{origin:state.origin||'site-original'}:{})});state={...state,revisionId:result.revisionId,articleId:result.id,locale:result.locale,fingerprint:result.fingerprint,draftVersion:result.draftVersion};persist();if(result.recovered&&JSON.stringify(result.content)!==JSON.stringify(draft.content))return save(draft);say(copy.serverSaved);return result;};
 const auto=createArticleAutosave({snapshot:()=>editor.snapshot(),save,canSave:()=>ready&&!needsRestore&&!state.submitted&&!['guest','unverified'].includes(ownerId)&&(typeof navigator==='undefined'||navigator.onLine!==false),onState:phase=>{if(cloudStatus)cloudStatus.textContent=cloudCopy[phase]||phase;},onError:error=>{say(error.message);if(error.code==='draft_conflict')showSaveConflict(error.server);}});
 editor.subscribe?.(()=>auto.notify());
 if(typeof window!=='undefined'){window.addEventListener('online',()=>auto.retry());window.addEventListener('pagehide',()=>{editor.persistLocal?.();persist();});window.addEventListener('beforeunload',()=>{editor.persistLocal?.();persist();});}
 const text=(tag,value)=>{const node=document.createElement(tag);node.textContent=value;return node;};
 const load=async()=>{const result=await call('/mine?offset='+offset),list=$('[data-article-proposals]');next=result.nextOffset;list.replaceChildren();for(const item of result.revisions){const card=text('section','');card.className='ve-article-proposal';card.append(text('h3',item.content.title||'未命名草稿'),text('p',`${item.locale} · ${{draft:'草稿',pending:'待审核',approved:'已批准',rejected:'已退回'}[item.status]}`));if(item.review_note)card.append(text('p',item.review_note));if(['draft','rejected'].includes(item.status)){const button=text('button',item.status==='draft'?'继续编辑':'修改后重新投稿');button.onclick=()=>run(async()=>{if(editor.hasLocalWork()&&!await confirmReplace())return;state={revisionId:item.status==='draft'?item.id:null,articleId:item.article_id,baseVersion:item.base_version,locale:item.locale,fingerprint:item.status==='draft'?item.fingerprint:null,draftVersion:item.draft_version,operationId:crypto.randomUUID()};if(item.status==='rejected'){try{const current=await call('/items/'+item.article_id+'?locale='+item.locale);state.baseVersion=current.article.version;}catch(error){if(item.base_version===0&&error.status===404){state.baseVersion=0;}else throw error;}}editor.restore(item.content,item.locale);needsRestore=false;persist();$('[data-article-dialog]').close();say('已载入文章提案。');});card.append(button);}if(item.status==='approved'){const link=createContextAction(copy.edit,`/${item.locale}/articles/submit/?id=${encodeURIComponent(item.article_id)}`);card.append(link);}list.append(card);}if(!result.revisions.length)list.append(text('p','暂无文章提案。'));$('[data-article-prev]').hidden=offset===0;$('[data-article-next]').hidden=next===null;};
 $('[data-article-save]').onclick=()=>run(async()=>{if(auto.paused&&!casConflict)auto.resume();if(['guest','unverified'].includes(ownerId))await save();else await auto.flush();});
 $('[data-article-submit]').onclick=()=>run(async()=>{await editor.validateRelations();if(['guest','unverified'].includes(ownerId)){await save();}else await auto.flush();if(auto.paused||needsRestore||!state.revisionId)throw Error(cloudCopy.conflict);if(admin){await call('/revisions/'+state.revisionId+'/publish','POST',{});state.submitted=true;auto.pause();persist();say('文章已公开。');receipt();return;}try{await call('/revisions/'+state.revisionId+'/submit','POST',{});}catch(error){if(error.status!==409){const probe=await call('/revisions/'+state.revisionId).catch(()=>null);if(probe?.revision?.status!=='pending')throw error;}else{const probe=await call('/revisions/'+state.revisionId);if(probe.revision.status!=='pending')throw error;}}state.submitted=true;auto.pause();persist();say(flowText.pending);receipt();});
 $('[data-article-mine]').onclick=()=>run(async()=>{offset=0;await load();openEditorPopover(root,$('[data-article-dialog]'));});
 $('[data-article-prev]').onclick=()=>run(async()=>{offset=Math.max(0,offset-20);await load();});
 $('[data-article-next]').onclick=()=>run(async()=>{if(next!==null){offset=next;await load();}});
 $('[data-article-new]').onclick=async()=>{if(busy)return;if(editor.hasLocalWork()&&!await confirmReplace())return;const url=new URL(location.href);url.search='';url.searchParams.set('draft',crypto.randomUUID());if(admin)url.searchParams.set('admin','1');const related=new URL(location.href).searchParams.get('related');if(related)url.searchParams.set('related',related);editor.prepareNavigation?.();location.href=url.href;};
 run(async()=>{if(admin)await call('/management-drafts?offset=0');if(requestedRevision){needsRestore=true;const {revision:item}=await call('/revisions/'+encodeURIComponent(requestedRevision));if(editor.hasLocalWork()&&!await confirmReplace())return;let baseVersion=item.base_version;if(item.status==='rejected'){try{const current=await call('/items/'+item.article_id+'?locale='+item.locale);baseVersion=current.article.version;}catch(error){if(item.base_version!==0||error.status!==404)throw error;}}state={revisionId:item.status==='rejected'?null:item.id,articleId:item.article_id,baseVersion,locale:item.locale,fingerprint:item.status==='draft'?item.fingerprint:null,draftVersion:item.draft_version,operationId:crypto.randomUUID(),submitted:item.status==='pending'||item.status==='approved'};editor.restore(item.content,item.locale);needsRestore=false;persist();say(item.review_note||({pending:'当前稿件正在审核，暂不能重复提交。',approved:'此稿件已通过，可从创作者中心继续完善。',draft:'已载入服务端草稿。',rejected:'已载入退回稿，请根据审核意见修改。'})[item.status]);if(item.status==='pending')receipt();return;}if(requestedId&&!state.articleId){needsRestore=true;const {article,permissions}=await call('/items/'+encodeURIComponent(requestedId)+'?locale='+locale);if(!permissions?.canEdit)throw Error('没有编辑此文章的权限。');state={articleId:article.id,baseVersion:article.version,locale:article.locale,origin:article.origin};needsRestore=false;if(editor.hasLocalWork()){persist();say('已恢复本地编辑内容，可继续保存为此文章的修改提案。');return;}editor.restore(article,article.locale);persist();}else if(state.revisionId&&!editor.hasLocalWork()){needsRestore=true;const {revision:item}=await call('/revisions/'+encodeURIComponent(state.revisionId));state.fingerprint=item.fingerprint;state.draftVersion=item.draft_version;state.submitted=item.status!=='draft';editor.restore(item.content,item.locale);needsRestore=false;persist();say(cloudCopy.cloudRestore);}if(state.submitted&&state.revisionId)receipt();say(state.submitted?(admin?'当前文章已公开。':'当前提案已提交审核，可在我的提案中查看状态。'):'');}).finally(()=>{ready=true;if(editor.hasLocalWork()&&!state.submitted&&!needsRestore)auto.notify();});
 return auto;
}
