import {uploadGalleryFiles} from '../lib/galleryUploadQueue.mjs';
import {formatBytes,uploadLimits} from '../lib/uploadPresentation.mjs';
import {showContributionReceipt} from '../lib/submissionReceipt.mjs';
import {galleryQueueSummary} from '../lib/galleryQueue.mjs';
import {imageViewer} from '../lib/imageViewer.mjs';
import {galleryDraft,galleryDraftKey,listGalleryDrafts} from '../lib/galleryDraftStore.mjs';
import {GalleryDraftController} from '../lib/galleryDraftController.mjs';
import {mountGalleryDraftStatus} from '../lib/galleryDraftStatus.mjs';
import {findExistingGalleryFile} from '../lib/galleryFileIdentity.mjs';
import {state,refreshAuth} from './accountStore.js';
const root=document.querySelector('[data-creation-uploader]');
if(root){
 const layout=JSON.parse(root.dataset.layoutCopy||'{}');
 const $=s=>root.querySelector(s),all=s=>[...root.querySelectorAll(s)];
 const text=(tag,value)=>{const e=document.createElement(tag);e.textContent=value;return e;};
 const c=JSON.parse(root.dataset.copy||'{}'),format=(value,parts)=>String(value).replace(/\{(\w+)\}/g,(_,key)=>String(parts[key]??''));
 let active='set-1',serial=1,files=[],selectedFile=null,simulating=false,owner=null,batch=null,saveTimer,hydrating=false,dirty=false,disposed=false,characters=[],draftController=null,draftId=null,stageFlight=null,localFilesUnavailable=false;
 const draftStatus=mountGalleryDraftStatus(root,root.dataset.locale||'zh',()=>draftController);
 const formCache=new Map();
 const api=document.querySelector('[data-gallery-api]').dataset.galleryApi.replace(/\/$/,'');
 const admin=new URLSearchParams(location.search).get('admin')==='1';
 const controller=new AbortController();
 const locale=root.dataset.locale||'zh';
 if(admin){
  const page=document.querySelector('.gallery-manage-shell');
  const intro=document.querySelector('.gallery-manage-shell .workspace-heading p:last-child');
  if(intro)intro.textContent=page?.dataset.adminIntro||intro.textContent;
  const back=document.querySelector('.gallery-manage-shell .workspace-back');
  if(back){back.href=api+'/admin/content?type=gallery';back.querySelector('span:last-child').textContent=c.manage;}
 }
 const flowText={submitted:c.submitted};
 const returnTo=new URLSearchParams(location.search).get('returnTo');
 const batchUrl=id=>{const url=new URL(location.pathname,location.origin);url.searchParams.set('batch',id);if(returnTo)url.searchParams.set('returnTo',returnTo);if(admin)url.searchParams.set('admin','1');return url.pathname+url.search;};
 const receipt=id=>{showContributionReceipt(root,{id,state:admin?c.published:flowText.submitted,href:admin?api+'/admin/content?type=gallery':`/${locale}/account/creator/?recordType=gallery&record=${encodeURIComponent(id)}`,...(admin?{title:c.publishedTitle,recordLabel:c.batchId,linkLabel:c.manage}:{})});root.dataset.complete='';};
 if(returnTo){try{const target=new URL(returnTo,location.origin);if(target.origin===location.origin&&/^\/(zh|zh-tw|zh-hk|ja|en)\/account\/creator\/$/.test(target.pathname)){const back=document.querySelector('.gallery-manage-shell .workspace-back');if(back){back.href=target.pathname+target.search;back.textContent='← '+c.creator;}}}catch{}}
 const template=$('[data-set]').cloneNode(true);
 const metadata=set=>Object.fromEntries([...set.querySelectorAll('[name]')].map(input=>[input.name,input.name==='tags'?input.value.split(/[,，]/).map(x=>x.trim()).filter(Boolean):input.value]));
 const manifest=()=>({sets:sets().map(set=>({id:set.dataset.set,setId:set.dataset.existing||null,baseVersion:Number(set.dataset.version)||0,metadata:metadata(set),images:files.filter(f=>f.set===set.dataset.set).map(f=>({fileId:f.id,metadata:Object.fromEntries(['title','notes','sourceUrl','sourceTitle','author','rightsBasis','rightsEvidence'].filter(k=>f[k]).map(k=>[k,f[k]]))}))}))});
 const request=async(path,body,method=body?'POST':'GET')=>{const url=new URL(api+'/api/gallery'+path);if(owner)url.searchParams.set('accountId',owner);const response=await fetch(url,{method,credentials:'include',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(20000)]),headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error?.message||c.serviceError),{status:response.status});if(disposed)throw Error(c.accountChanged);return data;};
 const adminRequest=async(path,body)=>{const response=await fetch(api+'/api/admin/gallery'+path,{method:body?'POST':'GET',credentials:'include',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(20000)]),headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error?.message||c.adminError),{status:response.status});return data;};
 const snapshot=()=>({manifest:manifest(),ownerId:owner,files:files.map(({url,...file})=>({...file,state:file.state==='staged'?'staged':'queued'}))});
 async function persistSnapshot(value){try{await galleryDraft('put',galleryDraftKey(owner,draftId),value);localFilesUnavailable=false;dirty=false;}catch{localFilesUnavailable=true;await galleryDraft('put',galleryDraftKey(owner,draftId),{...value,files:value.files.map(({file,...row})=>({...row,fileInfo:{name:file?.name,size:file?.size,type:file?.type}}))});dirty=true;status(c.localFull);}}
 function setupDraft(local){draftId=local?.id||batch?.id||crypto.randomUUID();draftController=new GalleryDraftController({id:draftId,kind:'sets',batch,version:local?.version??batch?.version,readManifest:manifest,readSnapshot:snapshot,saveLocal:persistSnapshot,request:(path,method,body)=>request(path,body,method),onState:value=>{draftStatus(value);index();},onBatch:value=>{batch=value;history.replaceState(null,'',batchUrl(draftId));},applyRemote:remote=>restore(null,remote)});if(local?.conflict||local&&batch&&local.version!==batch.version){draftController.conflict={batch};draftController.cloudState='conflict';draftController.emit();}else if(local?.cloudPending)draftController.changed();else draftController.emit();}
 async function persist(){if(!owner||hydrating||disposed||!draftController)return;await draftController.persist();}
 function changed(){if(hydrating||disposed||!draftController)return;dirty=true;draftController.changed();}
 async function saveRemote(){return draftController.sync();}

 const status=message=>$('[data-upload-status]').textContent=message;
 const sets=()=>all('[data-set]');
 const setName=(set,i)=>set.querySelector('[name=title]').value.trim()||format(c.setName,{n:String(i+1).padStart(2,'0')});
 function queueState(){return galleryQueueSummary(sets().map((set,i)=>({id:set.dataset.set,title:setName(set,i),character:set.querySelector('[name=character]').value})),files);}
 function index(){
  const nav=$('[data-set-index]');nav.replaceChildren();
  sets().forEach((set,i)=>{const name=setName(set,i),count=files.filter(f=>f.set===set.dataset.set).length,link=text('a',`${name} · ${count} ${c.photosUnit}`);link.href='#'+set.id;set.dataset.active=String(set.dataset.set===active);if(set.dataset.set===active)link.setAttribute('aria-current','location');link.onclick=()=>{active=set.dataset.set;index();};nav.append(link);set.querySelector('[data-remove-set]').disabled=sets().length===1||count>0||simulating;set.querySelector('[data-remove-set]').title=count?c.removePhotosFirst:'';set.querySelector('[data-set-photo-count]').textContent=`${count} ${c.photosUnit}`;set.querySelectorAll('[data-select-set],[data-file-picker]').forEach(button=>button.disabled=!owner||simulating||disposed);set.querySelector('h3').textContent=name;set.querySelector('.creation-caption').textContent=`${String(i+1).padStart(2,'0')} / SET`;const role=characters.find(value=>value.id===set.querySelector('[name=character]').value),form=set.querySelector('[name=form]').value.trim();set.querySelector('[data-set-destination]').textContent=role?format(c.destination,{name:role.labels?.[locale]||role.name,form:form||c.allUnclassified,count}):c.destinationEmpty;});
  const summary=queueState();$('[data-add-set]').disabled=simulating||disposed;
  $('[data-total-progress]').value=files.length?files.reduce((total,file)=>total+(file.progress||0),0)/files.length:0;
  $('[data-upload-count]').textContent=format(c.uploadCount,{photos:summary.total,sets:sets().length,staged:summary.staged})+(summary.failed?format(c.failedCount,{count:summary.failed}):'');
  const upload=$('[data-simulate-upload]'),submit=$('[data-submit-batch]');upload.disabled=!owner||!summary.total||!summary.pending||simulating||Boolean(stageFlight)||disposed||Boolean(draftController?.conflict);submit.disabled=!owner||!summary.ready||simulating||Boolean(stageFlight)||disposed||Boolean(draftController?.conflict);
  if(admin)submit.textContent=c.publishAll;
  upload.textContent=simulating?c.processing:summary.total&&!summary.pending?c.allStaged:summary.failed?format(c.retryUnfinished,{count:summary.pending}):`${c.uploadAll}${summary.pending?`（${summary.pending}）`:''}`;
  upload.dataset.tone=summary.ready?'secondary':'primary';submit.dataset.tone=summary.ready?'primary':'secondary';
  const issues=$('[data-upload-issues]');issues.replaceChildren();for(const issue of summary.issues){const li=text('li',''),button=text('button',issue.message);button.type='button';button.onclick=()=>{const set=sets().find(s=>s.dataset.set===issue.set);set?.scrollIntoView({block:'center',behavior:'smooth'});set?.querySelector(issue.field==='character'?'[name=character]':'[data-select-set]')?.focus({preventScroll:true});};li.append(button);issues.append(li);}issues.hidden=!summary.total||!summary.issues.length;
 }
 function roleOptions(set,query=''){const select=set.querySelector('[name=character]'),value=select.value;select.replaceChildren(new Option(c.chooseRole,''));for(const role of characters){if(role.id!==value&&query&&!`${role.name} ${role.id}`.toLowerCase().includes(query.toLowerCase()))continue;select.add(new Option(role.labels?.[locale]||role.name,role.id));}select.value=value;}
 async function formOptions(set){const role=set.querySelector('[name=character]').value,list=set.querySelector('[data-form-options]');if(!list)return;list.replaceChildren();if(!role)return;try{if(!formCache.has(role)){const data=await request('/sets/facets?character='+encodeURIComponent(role));formCache.set(role,[...new Set(data.facets.map(row=>row.form).filter(Boolean))]);}if(!set.isConnected||set.querySelector('[name=character]').value!==role)return;for(const form of formCache.get(role))list.append(new Option(form,form));}catch{/* A new form remains editable even when suggestions cannot load. */}}
 function preview(item){selectedFile=item.id;}
 function openPhoto(item,trigger){preview(item);const group=files.filter(f=>f.set===item.set);imageViewer().open(group.map(f=>({src:f.url,title:f.title||f.file.name,notes:`${formatBytes(f.file.size)} · ${f.width||'—'} × ${f.height||'—'} px`})),group.indexOf(item),trigger);}
 function progress(item){const row=root.querySelector(`[data-file-id="${item.id}"]`);if(!row)return;const bar=row.querySelector('progress');if(item.state==='uploading'&&item.progress===null)bar.removeAttribute('value');else bar.value=item.progress||0;row.querySelector('[data-file-state]').textContent=item.error|| (item.decodeError?c.decodeFailed:item.state==='staged'?(admin?c.stagedAdmin:c.staged):item.state==='saving'?c.saving:item.state==='uploading'?`${item.progress??'…'}% · ${formatBytes(item.loaded)} / ${formatBytes(item.total)}`:`${c.queued} · ${formatBytes(item.file.size)}`);}
 function render(){all('[data-image-list]').forEach(list=>list.replaceChildren());for(const set of sets()){const items=files.filter(f=>f.set===set.dataset.set);items.forEach((item,i)=>{
 const row=text('div','');row.className='creation-image-row';row.dataset.fileId=item.id;row.dataset.duplicate=String(Boolean(item.existingAsset));
 const thumb=text('button','');thumb.type='button';thumb.className='creation-image-thumbnail';thumb.setAttribute('aria-label',format(c.previewFile,{name:item.file.name}));const img=new Image();img.src=item.url;img.alt=item.file.name;thumb.append(img);thumb.onclick=()=>openPhoto(item,thumb);
 const data=text('div','');data.className='creation-image-data';data.append(text('strong',item.file.name),text('small',`${formatBytes(item.file.size)} · ${item.width?`${item.width} × ${item.height} px`:c.readingSize} · ${item.file.type.split('/')[1].toUpperCase()}`));
 const fields=text('div','');fields.className='creation-image-inputs';for(const [key,label]of [['title',c.photoTitle],['notes',c.photoNotes],['sourceUrl',c.photoSource]]){const field=text('label',label),input=document.createElement('input');input.type=key==='sourceUrl'?'url':'text';input.value=item[key]||'';input.placeholder=key==='sourceUrl'?c.photoSourceHint:key==='title'?c.photoTitleHint:c.photoNotesHint;input.oninput=()=>{item[key]=input.value;changed();};field.append(input);fields.append(field);}const perPhoto=document.createElement('details');perPhoto.className='creation-photo-details';const hint=text('p',layout.singleHint);hint.className='submission-hint';perPhoto.append(text('summary',layout.singleDetails),hint,fields);data.append(perPhoto);
 const rights=document.createElement('details');rights.className='creation-photo-rights';rights.append(text('summary',c.photoRights));const rightsFields=text('div','');rightsFields.className='creation-image-inputs';for(const [key,label]of [['author',c.photoAuthor],['sourceTitle',c.photoOrigin],['rightsEvidence',c.rightsEvidence]]){const field=text('label',label),input=document.createElement('input');input.type='text';input.value=item[key]||'';input.oninput=()=>{item[key]=input.value;changed();};field.append(input);rightsFields.append(field);}const basis=text('label',c.independentBasis),basisSelect=document.createElement('select');for(const [value,label]of [['',c.groupBasis],['official',c.official],['original',c.original],['authorized',c.authorized]])basisSelect.append(new Option(label,value));basisSelect.value=item.rightsBasis||'';basisSelect.onchange=()=>{item.rightsBasis=basisSelect.value;changed();};basis.append(basisSelect);rightsFields.append(basis);rights.append(rightsFields);perPhoto.append(rights);
 const tools=text('div','');tools.className='creation-image-tools';for(const [key,label,fn]of [['cover',i===0?c.cover:c.makeCover,()=>{files=files.filter(f=>f!==item);files.unshift(item);render();}],['up',c.moveUp,()=>{const before=items[i-1];if(!before)return;const a=files.indexOf(item),b=files.indexOf(before);[files[a],files[b]]=[files[b],files[a]];render();}],['down',c.moveDown,()=>{const after=items[i+1];if(!after)return;const a=files.indexOf(item),b=files.indexOf(after);[files[a],files[b]]=[files[b],files[a]];render();}],['remove',c.remove,()=>{if(simulating||['uploading','saving','checking'].includes(item.state))return;files=files.filter(f=>f!==item);URL.revokeObjectURL(item.url);render();if(selectedFile===item.id){if(files.length)preview(files[0]);else{selectedFile=null;}}}]]){const button=text('button',label);button.type='button';button.onclick=fn;button.disabled=simulating||(key==='remove'&&['uploading','saving','checking'].includes(item.state))||(key==='up'&&i===0)||(key==='down'&&i===items.length-1);if(key==='cover'&&i===0)button.setAttribute('aria-pressed','true');tools.append(button);}if(item.existingAsset?.kind==='public'){const existing=text('a',c.existingImage||c.someFailed);existing.href=`/${locale}/gallery/?photo=${encodeURIComponent(item.existingAsset.id)}`;existing.target='_blank';existing.rel='noopener';data.append(existing);}if(item.state==='failed'&&!item.existingAsset){const retry=text('button',c.retryPhoto);retry.type='button';retry.onclick=()=>void stagePending([item]);tools.append(retry);}data.append(tools);const line=text('p','');line.dataset.fileState='';line.className='creation-image-state';const bar=document.createElement('progress');bar.max=100;bar.value=item.progress||0;bar.setAttribute('aria-label',format(c.fileProgress,{name:item.file.name}));data.append(line,bar);row.append(thumb,data);set.querySelector('[data-image-list]').append(row);progress(item);
 });}index();changed();}
 async function addFiles(list,setId=active){if(simulating||disposed||!owner)return;const messages=[];for(const file of list){if(files.length>=uploadLimits.batchFiles){messages.push(c.batchLimit);break;}if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)){messages.push(format(c.unsupported,{name:file.name}));continue;}if(file.size>uploadLimits.fileBytes){messages.push(format(c.tooLarge,{name:file.name}));continue;}const item={id:crypto.randomUUID(),set:setId,file,url:URL.createObjectURL(file),state:'queued',progress:0};files.push(item);const image=new Image();image.src=item.url;try{await image.decode();item.width=image.naturalWidth;item.height=image.naturalHeight;}catch{item.decodeError=true;}render();preview(item);}status(messages.length?messages.join('；'):c.added);await persist();void stagePending();}
 root.addEventListener('change',event=>{if(!event.target.matches('[data-file-picker]'))return;const set=event.target.closest('[data-set]');void addFiles([...event.target.files],set.dataset.set);event.target.value='';});
 root.addEventListener('click',event=>{const old=event.target.closest('[data-set]');if(event.target.closest('[data-remove-set]')&&old&&!files.some(f=>f.set===old.dataset.set)&&sets().length>1){old.remove();if(active===old.dataset.set)active=sets()[0].dataset.set;index();changed();return;}const trigger=event.target.closest('[data-select-set]');if(trigger){active=trigger.dataset.selectSet;index();trigger.closest('[data-set]').querySelector('[data-file-picker]').click();}});
 root.addEventListener('input',event=>{if(event.target.matches('[data-character-filter]')){roleOptions(event.target.closest('[data-set]'),event.target.value);return;}if(event.target.matches('[name=title],[name=form]'))index();changed();});
 root.addEventListener('change',event=>{if(event.target.matches('[name=character]')){index();void formOptions(event.target.closest('[data-set]'));changed();}});
 root.addEventListener('dragover',event=>{const zone=event.target.closest('[data-drop-set]');if(zone){event.preventDefault();zone.dataset.dragging='';}});root.addEventListener('dragleave',event=>event.target.closest('[data-drop-set]')?.removeAttribute('data-dragging'));root.addEventListener('drop',event=>{const zone=event.target.closest('[data-drop-set]');if(!zone)return;event.preventDefault();zone.removeAttribute('data-dragging');active=zone.dataset.dropSet;void addFiles([...event.dataTransfer.files],active);});
 root.addEventListener('paste',event=>{const set=event.target.closest('[data-set]');const images=[...(event.clipboardData?.files||[])].filter(file=>file.type.startsWith('image/'));if(images.length&&owner&&!disposed&&!simulating){event.preventDefault();void addFiles(images,set?.dataset.set||active);}});
 $('[data-add-set]').onclick=()=>{if(simulating||disposed)return;serial++;const node=template.cloneNode(true);node.dataset.set=`set-${serial}`;node.id=`creation-set-${serial}`;node.querySelector('.creation-caption').textContent=`${String(serial).padStart(2,'0')} / SET`;node.querySelector('h3').textContent=format(c.numberedSet,{n:serial});node.querySelector('[data-image-list]').replaceChildren();node.querySelectorAll('[name]').forEach(e=>{e.value='';e.id=`set-${serial}-${e.name}`;e.closest('label')?.setAttribute('for',e.id);});node.querySelector('[data-form-options]').id=`set-${serial}-forms`;node.querySelector('[name=form]').setAttribute('list',`set-${serial}-forms`);node.querySelectorAll('[data-select-set]').forEach(e=>e.dataset.selectSet=node.dataset.set);node.querySelector('[data-drop-set]').dataset.dropSet=node.dataset.set;$('[data-set-container]').append(node);roleOptions(node);active=node.dataset.set;index();changed();node.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'instant':'smooth'});};
 async function uploadItems(items){
  if(disposed)return;const jobs=[];
  for(const item of items){if(item.state==='staged')continue;if(item.decodeError){item.state='failed';item.error=c.decodeFailed;progress(item);continue;}item.state='checking';progress(item);const existing=item.file instanceof Blob?await findExistingGalleryFile(item,files,(path,method,body)=>request(path,body,method)):null;if(existing){item.existingAsset=existing;item.state='failed';item.error=existing.kind==='public'?(c.existingImage||c.someFailed):(c.duplicateFile||c.someFailed);progress(item);continue;}if(!(item.file instanceof Blob)){item.state='failed';item.error=c.missingFile;progress(item);continue;}item.error='';item.state='uploading';progress(item);jobs.push({id:item.id,file:item.file,metadata:{name:item.file.name,width:item.width,height:item.height},url:api+'/api/gallery/uploads/'+batch.id+'/'+item.id+'?accountId='+encodeURIComponent(owner)});}
  try{await uploadGalleryFiles(jobs,{locale,signal:controller.signal,onProgress:(id,p)=>{if(disposed)return;const item=items.find(item=>item.id===id);item.state=p.phase;item.progress=p.percent;item.loaded=p.loaded;item.total=p.total;progress(item);$('[data-total-progress]').value=files.reduce((s,f)=>s+(f.progress||0),0)/files.length;},onResult:({id,error})=>{if(disposed)return;const item=items.find(item=>item.id===id);item.state=error?'failed':'staged';item.error=error?.message||'';if(!error)item.progress=100;progress(item);changed();}});}finally{await persist();}
 }
 async function stagePending(only){
  if(stageFlight||simulating||disposed||!draftController||draftController.conflict)return stageFlight;
  if(only)for(const item of only)if(item.state==='failed'&&!item.existingAsset)item.state='queued';
  const pending=()=>files.filter(item=>item.state==='queued');
  stageFlight=(async()=>{try{await draftController.ensureBatch();while(pending().length&&!disposed)await uploadItems(pending());if(!disposed){status(files.length&&files.every(file=>file.state==='staged')?(admin?c.allStagedAdmin:c.allStagedReview):c.someFailed);await quotaInfo();}}
   catch(error){if(!disposed){status(error.message);for(const item of files)if(['checking','uploading','saving'].includes(item.state)){item.state='failed';item.error=error.message;}}}finally{stageFlight=null;render();}})();index();return stageFlight;
 }
 $('[data-simulate-upload]').onclick=async()=>{for(const item of files)if(item.state==='failed'&&!item.existingAsset)item.state='queued';await stagePending();};
 $('[data-submit-batch]').onclick=async()=>{if(simulating||stageFlight||disposed||draftController?.conflict)return;if(queueState().issues.length){index();$('[data-upload-issues] button')?.click();return;}if(!sets().every(set=>[...set.querySelectorAll('input,textarea,select')].every(input=>input.reportValidity())))return;simulating=true;index();try{await saveRemote();if(admin){await adminRequest('/batches/'+batch.id+'/publish',{version:batch.version});}else{try{await request('/batches/'+batch.id+'/submit',{version:batch.version});}catch(error){const probe=await request('/batches/'+batch.id).catch(()=>null);if(probe?.batch?.status!=='submitted')throw error;}}batch={...batch,status:'submitted'};await galleryDraft('delete',galleryDraftKey(owner,draftId));draftController.close();dirty=false;status(admin?c.published:flowText.submitted);receipt(batch.id);disposed=true;}catch(error){status(error.message);}finally{simulating=false;index();}};
 async function quotaInfo(){
  const q=await request('/quota');
  $('[data-session-state]').textContent=c.ready;
  $('[data-quota-remaining]').textContent=String(q.remaining);
  $('[data-quota-limit]').textContent=String(q.limit);
  $('[data-session-concurrency]').textContent=String(q.concurrency);
  all('[data-session-stat]').forEach(item=>item.hidden=false);
  const expiry=$('[data-session-expiry]');expiry.hidden=!batch?.expires_at;
  if(batch?.expires_at){
   const raw=String(batch.expires_at),date=new Date(/[zZ]|[+-]\d\d:\d\d$/.test(raw)?raw:`${raw.replace(' ','T')}Z`);
   const value=$('[data-session-expiry-value]');value.textContent=Number.isNaN(date.getTime())?raw:new Intl.DateTimeFormat(locale==='ja'?'ja-JP':locale==='en'?'en-US':'zh-CN',{month:'numeric',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(date);
   value.title=`${raw} UTC`;
  }
 }
 async function restore(draft,remote){hydrating=true;files.forEach(f=>URL.revokeObjectURL(f.url));files=[];$('[data-set-container]').replaceChildren();const data=draft?.manifest||remote?.batch.manifest;if(!data?.sets?.length){$('[data-set-container]').append(template.cloneNode(true));hydrating=false;return;}
  for(const [i,set]of data.sets.entries()){const node=template.cloneNode(true);node.dataset.set=set.id;node.dataset.existing=set.setId||'';node.dataset.version=set.baseVersion||0;node.id='creation-'+set.id;node.querySelector('h3').textContent=format(c.numberedSet,{n:i+1});roleOptions(node);node.querySelectorAll('[name]').forEach(input=>{input.value=Array.isArray(set.metadata[input.name])?set.metadata[input.name].join(', '):set.metadata[input.name]||'';input.id=set.id+'-'+input.name;input.closest('label').htmlFor=input.id;});node.querySelector('[data-form-options]').id=set.id+'-forms';node.querySelector('[name=form]').setAttribute('list',set.id+'-forms');node.querySelectorAll('[data-select-set]').forEach(e=>e.dataset.selectSet=set.id);node.querySelector('[data-drop-set]').dataset.dropSet=set.id;node.querySelector('[data-image-list]').replaceChildren();$('[data-set-container]').append(node);void formOptions(node);
   for(const image of set.images){const local=draft?.files.find(f=>f.id===image.fileId),server=remote?.files.find(f=>f.id===image.fileId),file=local?.file||local?.fileInfo||{name:server?.name||c.fileNameMissing,size:server?.size||0,type:server?.mime_type||'image/png'},item={...local,...image.metadata,id:image.fileId,set:set.id,file,width:server?.width||local?.width,height:server?.height||local?.height,state:server?.state==='staged'?'staged':'queued',progress:server?.state==='staged'?100:0};item.url=file instanceof Blob?URL.createObjectURL(file):server?.previewUrl||'';if(!(file instanceof Blob)&&item.state!=='staged')item.error=c.missingFileShort;files.push(item);}
  }serial=Math.max(data.sets.length,...data.sets.map(s=>Number(s.id.replace('set-',''))||0));active=data.sets[0].id;render();if(files.length)preview(files[0]);hydrating=false;
 }
 async function initialize(){try{const viewer=await refreshAuth();owner=viewer?.userId;if(!owner){status(c.signInHint);const a=text('a',c.signIn);a.href=`/${locale}/account/?returnTo=`+encodeURIComponent(location.href);$('[data-session-state]').replaceChildren(a);index();return;}if(admin)await adminRequest('/catalog?offset=0');
  characters=(await request('/characters')).characters;roleOptions(template);sets().forEach(set=>roleOptions(set));
  const params=new URLSearchParams(location.search);let draft;const drafts=await listGalleryDrafts(owner).catch(()=>{status(c.storageUnavailable);return [];});const requested=new URLSearchParams(location.search).get('batch');draft=requested?drafts.find(value=>value.id===requested):!params.has('new')?drafts.find(value=>value.kind==='sets'):null;
  let id=params.get('batch');let setId=params.get('set');const revision=params.get('revision');if(params.get('edit'))setId=(await request('/items/'+encodeURIComponent(params.get('edit')))).item.setId;if(setId||revision){let resumeId=params.get('resumeDraft');if(!resumeId||!/^[-\w]{1,100}$/.test(resumeId)){resumeId=crypto.randomUUID();const url=new URL(location.href);url.searchParams.set('resumeDraft',resumeId);history.replaceState(null,'',url);}const path=`/${setId?'sets/'+encodeURIComponent(setId)+'/edit-batch':'set-revisions/'+encodeURIComponent(revision)+'/resubmit'}`;batch=(await (admin?adminRequest(path,{id:resumeId}):request(path,{id:resumeId}))).batch;id=batch.id;history.replaceState(null,'',batchUrl(id));draft=null;}
  id=id||draft?.id;if(id){const remote=await request('/batches/'+encodeURIComponent(id)).catch(error=>{if(draft?.id===id&&(error.status===404||!error.status))return null;throw error;});batch=remote?.batch;if(batch?.status==='submitted'){status(admin?c.published:flowText.submitted);receipt(batch.id);disposed=true;index();return;}if(batch&&batch.status!=='draft')throw Error(c.cancelled);await restore(draft?.id===id?draft:null,remote);history.replaceState(null,'',batchUrl(id));}else if(draft)await restore(draft,null);
  setupDraft(draft);await quotaInfo();index();if(files.some(file=>file.state==='queued'))void stagePending();}catch(error){status(error.message);$('[data-session-state]').textContent=c.unavailable;}}
 window.addEventListener('beforeunload',event=>{if(dirty||simulating||stageFlight||localFilesUnavailable&&files.some(file=>file.state!=='staged')||draftController?.localState==='saving'||draftController?.localState==='error'){event.preventDefault();event.returnValue='';}});
 window.addEventListener('kamitsubaki-account-state',()=>{if(owner&&state.viewer?.userId!==owner){void draftController?.persist().catch(()=>{});draftController?.close();disposed=true;controller.abort();imageViewer().close();files.forEach(f=>URL.revokeObjectURL(f.url));files=[];root.querySelectorAll('input,textarea,select').forEach(e=>e.value='');all('[data-image-list]').forEach(e=>e.replaceChildren());status(c.ownerChanged);index();}});
 window.addEventListener('online',()=>{if(!disposed&&draftController&&!draftController.conflict){void draftController.sync().catch(()=>{});void stagePending();}});
 window.addEventListener('pagehide',()=>void draftController?.persist().catch(()=>{}));
 index();void initialize();
}
