import {uploadGalleryFiles} from '../lib/galleryUploadQueue.mjs';
import {uploadLimits,formatBytes} from '../lib/uploadPresentation.mjs';
import {galleryDraft,galleryDraftKey,listGalleryDrafts} from '../lib/galleryDraftStore.mjs';
import {GalleryDraftController} from '../lib/galleryDraftController.mjs';
import {mountGalleryDraftStatus} from '../lib/galleryDraftStatus.mjs';
import {findExistingGalleryFile} from '../lib/galleryFileIdentity.mjs';
import {photoFieldLimits,updatePhotoTags,photoMetadataCopy} from '../lib/galleryPhotoMetadata.mjs';
import {refreshAuth,state} from './accountStore.js';

const root=document.querySelector('[data-photo-workbench]');
if(root){
 const $=selector=>root.querySelector(selector),api=root.dataset.api.replace(/\/$/,''),copy=JSON.parse(root.dataset.copy||'{}'),locale=root.dataset.locale;
 const create=(tag,value='')=>{const node=document.createElement(tag);node.textContent=value;return node;};
 let owner=null,batch=null,files=[],busy=false,busyAction='',entities=[],mediaTypes=[],disposed=false,draftController=null,draftId=null,stageFlight=null,selectedPhoto=null,localFilesUnavailable=false;
 const draftStatus=mountGalleryDraftStatus(root,locale,()=>draftController),metadataCopy=photoMetadataCopy(locale);
 const uploadController=new AbortController();
 const draftKey=()=>galleryDraftKey(owner,draftId);
 const say=(value,tone='info')=>{const status=$('[data-photo-status]');status.textContent=value;status.dataset.tone=tone;};
 const request=async(path,method='GET',body)=>{const url=new URL(api+'/api/gallery'+path);if(owner)url.searchParams.set('accountId',owner);const response=await fetch(url,{method,credentials:'include',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok)throw Object.assign(Error(data.error?.message||copy.failed),{status:response.status,code:data.error?.code,fileId:data.error?.fileId,itemId:data.error?.itemId});return data;};
 const defaults=()=>{const fields=Object.fromEntries([...root.querySelectorAll('[data-default]')].map(input=>[input.dataset.default,input.value.trim()]));return {...fields,mediaType:fields.mediaType||null,tags:fields.tags.split(/[,，]/).map(value=>value.trim()).filter(Boolean),entityIds:[...root.querySelectorAll('[data-entity-options] input:checked')].map(input=>input.value)};};
 const manifest=()=>({kind:'photos',defaults:defaults(),photos:files.map(file=>({fileId:file.id,metadata:Object.fromEntries(Object.entries(file.metadata).filter(([,value])=>value!==''&&value!==undefined))}))});
 function fieldsFromManifest(data){for(const [key,value] of Object.entries(data.defaults||{})){const input=root.querySelector(`[data-default="${key}"]`);if(input)input.value=Array.isArray(value)?value.join(', '):value||'';}root.querySelectorAll('[data-entity-options] input').forEach(input=>{input.checked=(data.defaults?.entityIds||[]).includes(input.value);});toggleEvidence();}
 const snapshot=()=>({manifest:manifest(),files:files.map(({url,...file})=>({...file,state:file.state==='staged'?'staged':'queued'})),ownerId:owner});
 async function persistSnapshot(value){try{await galleryDraft('put',draftKey(),value);localFilesUnavailable=false;}catch{localFilesUnavailable=true;await galleryDraft('put',draftKey(),{...value,files:value.files.map(({file,...row})=>row)});say(copy.localStorageFull,'error');}}
 function setupDraft(local){
  draftId=local?.id||batch?.id||crypto.randomUUID();
  draftController=new GalleryDraftController({id:draftId,kind:'photos',batch,version:local?.version??batch?.version,readManifest:manifest,readSnapshot:snapshot,saveLocal:persistSnapshot,request,onState:state=>{draftStatus(state);updateButtons();},onBatch:value=>{batch=value;const url=new URL(location.href);url.searchParams.set('batch',draftId);history.replaceState(null,'',url);},applyRemote:remote=>restoreFiles(remote.batch.manifest,null,remote)});
  if(local?.conflict||local&&batch&&local.version!==batch.version){draftController.conflict={batch};draftController.cloudState='conflict';draftController.emit();}
  else if(local?.cloudPending)draftController.changed();
  else draftController.emit();
 }
 async function saveLocal(){if(!owner||disposed||!draftController)return false;draftController.changed();return true;}
 async function saveRemote(){if(!draftController)throw Error(copy.loginFirst);await draftController.sync();return draftController.localState==='saved';}
 function updateButtons(){const can=Boolean(owner&&!busy&&!stageFlight&&!disposed&&!draftController?.conflict),editable=Boolean(owner&&!disposed&&busyAction!=='submit');for(const key of ['save','stage','submit']){const button=$(`[data-photo-${key}]`);button.disabled=!can;button.dataset.busy=String(busyAction===key);button.textContent=busyAction===key?copy[{save:'saving',stage:'staging',submit:'submitting'}[key]]:copy[key];}for(const input of root.querySelectorAll('[data-photo-files],[data-default],[data-entity-search],[data-entity-options] input'))input.disabled=!editable;const access=$('[data-photo-access]'),unavailable=state.auth==='unavailable';access.hidden=Boolean(owner)||state.auth==='checking';$('[data-photo-access-title]').textContent=unavailable?copy.authUnavailable:copy.loginFirst;$('[data-photo-access-note]').textContent=unavailable?copy.authUnavailableReason:copy.loginReason;$('[data-photo-access-login]').hidden=unavailable;$('[data-photo-access-retry]').hidden=!unavailable;drop.dataset.locked=String(!editable);$('[data-photo-count]').textContent=`${files.length} ${copy.photos} · ${files.filter(file=>file.state==='staged').length} ${copy.staged}`;}
 const begin=action=>{busy=true;busyAction=action;updateButtons();say(copy[{save:'saving',stage:'staging',submit:'submitting'}[action]],'progress');};
 const end=()=>{busy=false;busyAction='';updateButtons();};
 function showSuccess(){const dialog=$('[data-photo-success]');$('[data-photo-success-link]').href=$('[data-photo-receipt]').href;if(typeof dialog.showModal==='function')dialog.showModal();else dialog.setAttribute('open','');$('[data-photo-success-link]').focus();}
 function rowField(label,key,file,type='text'){const wrapper=create('label',label),input=document.createElement('input');input.type=type;input.value=Array.isArray(file.metadata[key])?file.metadata[key].join(', '):file.metadata[key]||'';input.maxLength=photoFieldLimits[key]||200;input.placeholder=key==='title'?'':copy.inherit;input.oninput=()=>{const value=input.value.trim();if(key==='tags')updatePhotoTags(file.metadata,value);else if(value)file.metadata[key]=value;else delete file.metadata[key];void saveLocal();};wrapper.append(input);return wrapper;}
 function rowSelect(label,key,file,options){const wrapper=create('label',label),select=document.createElement('select');for(const [value,text] of options)select.add(new Option(text,value));select.value=key==='mediaType'&&file.metadata[key]===null?'__none__':file.metadata[key]||'';select.onchange=()=>{if(select.value==='')delete file.metadata[key];else file.metadata[key]=select.value==='__none__'?null:select.value;void saveLocal();};wrapper.append(select);return wrapper;}
 function rowEntities(file){const section=create('div'),toggle=document.createElement('label'),checkbox=document.createElement('input'),options=create('div');section.className='gallery-photo-row__entities';toggle.className='gallery-photo-row__entity-toggle';checkbox.type='checkbox';checkbox.checked=Object.hasOwn(file.metadata,'entityIds');toggle.append(checkbox,create('span',copy.differentEntities));options.className='gallery-photo-row__entity-options';options.hidden=!checkbox.checked;for(const entity of entities){const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.value=entity.id;input.checked=file.metadata.entityIds?.includes(entity.id)||false;input.onchange=()=>{file.metadata.entityIds=[...options.querySelectorAll('input:checked')].map(item=>item.value);void saveLocal();};label.append(input,create('span',entity.labels?.[locale]||entity.name));options.append(label);}checkbox.onchange=()=>{if(checkbox.checked){file.metadata.entityIds=defaults().entityIds;options.querySelectorAll('input').forEach(input=>{input.checked=file.metadata.entityIds.includes(input.value);});}else delete file.metadata.entityIds;options.hidden=!checkbox.checked;void saveLocal();};section.append(toggle,options);return section;}
 function inspector(file,trigger){
  const dialog=$('[data-photo-inspector]');if(!dialog)return;selectedPhoto=file.id;
  const title=$('[data-photo-inspector-title]');if(title)title.textContent=file.metadata.title||file.name||copy.inspectorTitle;
  const body=$('[data-photo-inspector-body]');body.replaceChildren();
  if(file.url){const image=new Image();image.src=file.url;image.alt=file.metadata.title||file.name||'';image.decoding='async';image.dataset.photoInspectorPreview='';body.append(image);}
  const fields=create('div');fields.className='gallery-photo-row__fields';
  for(const [label,key,type] of [[copy.photoTitle,'title','text'],[copy.author,'author','text'],[copy.sourceTitle,'sourceTitle','text'],[copy.sourceUrl,'sourceUrl','url'],[copy.evidence,'rightsEvidence','text']])fields.append(rowField(label,key,file,type));
  const tags=create('div'),tagField=rowField(copy.tags,'tags',file),tagInput=tagField.querySelector('input'),clearLabel=create('label'),clearTags=document.createElement('input');
  clearLabel.className='gallery-photo-row__entity-toggle';clearTags.type='checkbox';clearTags.dataset.photoClearTags='';clearTags.checked=Array.isArray(file.metadata.tags)&&file.metadata.tags.length===0;tagInput.disabled=clearTags.checked;
  clearTags.onchange=()=>{tagInput.disabled=clearTags.checked;tagInput.value='';updatePhotoTags(file.metadata,'',{clear:clearTags.checked});void saveLocal();};clearLabel.append(clearTags,create('span',metadataCopy.clearTags));tags.append(tagField,clearLabel);fields.append(tags);
  fields.append(rowSelect(copy.purpose,'purpose',file,[['',copy.inherit],['gallery',copy.galleryPurpose],['entry',copy.entryPurpose]]),rowSelect(copy.basis,'rightsBasis',file,[['',copy.inherit],['official',copy.official],['original',copy.original],['authorized',copy.authorized]]),rowSelect(copy.type,'mediaType',file,[['',copy.inherit],['__none__',copy.noType],...mediaTypes.map(type=>[type.id,type.labels?.[locale]||type.labels?.zh||type.id])]));body.append(fields,rowEntities(file));
  if(file.reviewNote)body.append(create('p',`${copy.reviewReason}：${file.reviewNote}`));
  root.querySelectorAll('[data-photo-id]').forEach(row=>row.dataset.selected=String(row.dataset.photoId===file.id));
  dialog.returnTrigger=trigger;if(!dialog.open)dialog.showModal();
 }
 $('[data-photo-inspector-close]')?.addEventListener('click',()=>{const dialog=$('[data-photo-inspector]');dialog.close();dialog.returnTrigger?.focus();});
 function updateRows(){
  for(const file of files){const row=root.querySelector(`[data-photo-id="${file.id}"]`);if(!row)continue;
   const state=file.state==='staged'?copy.staged:file.state==='uploading'?(file.progress??'…')+'%':file.state==='saving'?copy.saving:file.state==='failed'?copy.failed:copy.queued;
   row.querySelector('[data-file-state]').textContent=`${formatBytes(file.file?.size||file.size||0)} · ${state}${file.error?' · '+file.error:''}`;
   row.dataset.state=file.state;row.dataset.duplicate=String(Boolean(file.existingAsset));
   row.querySelector('[data-photo-remove]').disabled=busyAction==='submit'||['uploading','saving'].includes(file.state);
   const retry=row.querySelector('[data-photo-retry]');retry.hidden=file.state!=='failed'||Boolean(file.existingAsset);retry.disabled=Boolean(stageFlight)||disposed;
  }updateButtons();
 }
 function render(){
  const list=$('[data-photo-list]');list.replaceChildren();if(!files.length)list.append(create('p',copy.empty));
  for(const file of files){
   const row=create('div');row.className='gallery-photo-row';row.dataset.photoId=file.id;row.dataset.selected=String(selectedPhoto===file.id);
   const preview=create('button');preview.type='button';preview.dataset.photoInspect='';preview.className='gallery-photo-row__preview';preview.setAttribute('aria-label',`${copy.inspectPhoto||copy.override} · ${file.name}`);const image=new Image();image.src=file.url||'';image.alt=file.metadata.title||file.name||'';image.loading='lazy';preview.append(image);preview.onclick=()=>inspector(file,preview);
   const body=create('div');body.className='gallery-photo-row__body';body.append(create('strong',file.name||'Photo'));const detail=create('small');detail.dataset.fileState='';body.append(detail);
   const tools=create('div');tools.className='gallery-photo-row__tools';const edit=create('button',copy.inspectPhoto||copy.override);edit.type='button';edit.onclick=()=>inspector(file,edit);const retry=create('button',copy.retryPhoto||copy.stage);retry.type='button';retry.dataset.photoRetry='';retry.onclick=()=>void stagePending([file]);const remove=create('button',copy.remove);remove.type='button';remove.dataset.photoRemove='';remove.onclick=()=>{if(['uploading','saving'].includes(file.state)||busyAction==='submit')return;if(file.url?.startsWith('blob:'))URL.revokeObjectURL(file.url);files=files.filter(item=>item!==file);render();void saveLocal();};tools.append(edit,retry,remove);body.append(tools);
   if(file.existingAsset?.kind==='public'){const link=create('a',copy.existingImage||copy.duplicateFile);link.href=`/${locale}/gallery/?photo=${encodeURIComponent(file.existingAsset.id)}`;link.target='_blank';link.rel='noopener';body.append(link);}
   if(!(file.file instanceof Blob)&&file.state!=='staged'){const rebind=create('label',copy.reselectFile),input=document.createElement('input');input.type='file';input.accept='image/png,image/jpeg,image/webp,image/gif';input.onchange=()=>{const replacement=input.files?.[0];if(!replacement)return;if(!['image/png','image/jpeg','image/webp','image/gif'].includes(replacement.type)||replacement.size>uploadLimits.fileBytes){say(copy.invalidFile,'error');return;}if(file.url?.startsWith('blob:'))URL.revokeObjectURL(file.url);Object.assign(file,{file:replacement,name:replacement.name,size:replacement.size,url:URL.createObjectURL(replacement),state:'queued',error:'',sha256:null,existingAsset:null});render();void saveLocal();void stagePending([file]);};rebind.append(input);body.append(rebind);}
   if(file.reviewNote)body.append(create('p',`${copy.reviewReason}：${file.reviewNote}`));row.append(preview,body);list.append(row);
  }updateRows();
 }
 function toggleEvidence(){const authorized=$('[data-default="rightsBasis"]').value==='authorized';$('[data-evidence-field]').hidden=!authorized;}
 async function addFiles(input){if(!owner||disposed){say(copy.loginFirst,'error');return;}if(busyAction==='submit')return;const errors=[];for(const file of input){if(files.length>=uploadLimits.batchFiles){errors.push(copy.tooMany);break;}if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>uploadLimits.fileBytes){errors.push(`${file.name}：${copy.invalidFile}`);continue;}files.push({id:crypto.randomUUID(),file,name:file.name,size:file.size,url:URL.createObjectURL(file),metadata:{},state:'queued'});}render();say(errors.length?errors.join('；'):copy.queued,errors.length?'error':'info');await saveLocal();void stagePending();}
 $('[data-photo-files]').onchange=event=>{void addFiles([...event.target.files]);event.target.value='';};
 root.addEventListener('paste',event=>{const images=[...(event.clipboardData?.files||[])].filter(file=>file.type.startsWith('image/'));if(!images.length||!owner||disposed||busyAction==='submit')return;event.preventDefault();void addFiles(images);});
 const drop=$('[data-photo-drop]');drop.ondragover=event=>{event.preventDefault();if(owner&&!busy&&!disposed)drop.dataset.dragging='';};drop.ondragleave=()=>delete drop.dataset.dragging;drop.ondrop=event=>{event.preventDefault();delete drop.dataset.dragging;void addFiles([...event.dataTransfer.files]);};
 root.querySelectorAll('[data-default]').forEach(input=>input.addEventListener('input',()=>{if(input.dataset.default==='rightsBasis')toggleEvidence();void saveLocal();}));
 $('[data-entity-search]').oninput=event=>{const q=event.target.value.trim().toLocaleLowerCase();root.querySelectorAll('[data-entity-options] label').forEach(label=>{label.hidden=Boolean(q&&!label.textContent.toLocaleLowerCase().includes(q));});};
 $('[data-entity-options]').onchange=()=>void saveLocal();
 async function stageFiles(items){
  const jobs=[];for(const file of items){if(file.state==='staged')continue;if(!(file.file instanceof Blob)){file.state='failed';file.error=copy.reselectFile;continue;}
   file.state='checking';updateRows();const existing=await findExistingGalleryFile(file,files,request);if(disposed)return;
   if(existing){file.existingAsset=existing;file.state='failed';file.error=existing.kind==='public'?(copy.existingImage||copy.duplicateFile):copy.duplicateFile;continue;}
   let width=0,height=0;try{const bitmap=await createImageBitmap(file.file);width=bitmap.width;height=bitmap.height;bitmap.close();}catch{}
   file.error='';file.state='uploading';jobs.push({id:file.id,file:file.file,name:file.name,metadata:{name:file.name,width,height},url:api+'/api/gallery/uploads/'+encodeURIComponent(batch.id)+'/'+encodeURIComponent(file.id)+'?accountId='+encodeURIComponent(owner)});
  }
  updateRows();try{await uploadGalleryFiles(jobs,{locale,signal:uploadController.signal,onProgress:(id,p)=>{if(disposed)return;const file=items.find(file=>file.id===id);file.progress=p.percent;file.state=p.phase;updateRows();},onResult:({id,error})=>{if(disposed)return;const file=items.find(file=>file.id===id);file.state=error?'failed':'staged';file.error=error?.message||'';updateRows();void saveLocal();}});}finally{if(!disposed){render();await saveLocal();}}
 }
 async function stagePending(only){
  if(stageFlight||disposed||!draftController||draftController.conflict)return stageFlight;
  const pending=()=>files.filter(file=>file.state==='queued');
  if(only)for(const file of only)if(!file.existingAsset&&file.state==='failed')file.state='queued';
  stageFlight=(async()=>{try{await draftController.ensureBatch();while(pending().length&&!disposed){const queue=pending();await stageFiles(queue);}if(!disposed)say(files.length&&files.every(file=>file.state==='staged')?`${copy.staged} · ${copy.submit}`:copy.readyStatus);}
   catch(error){if(!disposed){say(error.message,'error');for(const file of files)if(['uploading','saving','checking'].includes(file.state)){file.state='failed';file.error=error.message;}}}
   finally{stageFlight=null;render();}})();updateButtons();return stageFlight;
 }
 $('[data-photo-save]').onclick=async()=>{if(busy)return;if(!files.length){say(copy.chooseFirst,'error');return;}begin('save');try{const savedLocally=await saveRemote();say(savedLocally?copy.save+' ✓':copy.localStorageFull,savedLocally?'success':'error');}catch(error){if(!disposed)say(error.message,'error');}finally{end();}};
 $('[data-photo-stage]').onclick=async()=>{if(!files.length){say(copy.chooseFirst,'error');return;}for(const file of files)if(file.state==='failed'&&!file.existingAsset)file.state='queued';await stagePending();};
 $('[data-photo-submit]').onclick=async()=>{if(busy||stageFlight||draftController?.conflict)return;if(!files.length){say(copy.chooseFirst,'error');return;}if(files.some(file=>file.state!=='staged')){say(copy.stageFirst,'error');$('[data-photo-stage]').focus();return;}begin('submit');try{await saveRemote();await request('/batches/'+encodeURIComponent(batch.id)+'/submit','POST',{version:batch.version});try{await galleryDraft('delete',draftKey());}catch{}draftController.close();disposed=true;say(copy.review,'success');$('[data-photo-receipt]').href=`/${locale}/account/creator/?recordType=gallery&record=${encodeURIComponent(batch.id)}`;$('[data-photo-receipt]').hidden=false;showSuccess();}catch(error){if(error.code==='duplicate_image'){const duplicate=files.find(file=>file.id===error.fileId);if(duplicate){duplicate.duplicate=true;duplicate.error=error.message;render();void saveLocal();}}say(error.message,'error');}finally{end();}};
 $('[data-photo-success-close]').onclick=()=>{const dialog=$('[data-photo-success]');if(typeof dialog.close==='function')dialog.close();else dialog.removeAttribute('open');};
 function restoreFiles(data,local,remote){
  const inspector=$('[data-photo-inspector]');if(inspector?.open)inspector.close();$('[data-photo-inspector-body]')?.replaceChildren();selectedPhoto=null;
  files.forEach(file=>{if(file.url?.startsWith('blob:'))URL.revokeObjectURL(file.url);});fieldsFromManifest(data||{});
  files=(data?.photos||[]).map(photo=>{const saved=local?.files?.find(file=>file.id===photo.fileId),server=remote?.files.find(file=>file.id===photo.fileId),file=saved?.file;return {...saved,id:photo.fileId,metadata:photo.metadata||{},file,name:saved?.name||server?.name||'Photo',size:saved?.size||server?.size||0,url:file instanceof Blob?URL.createObjectURL(file):server?.previewUrl||'',state:server?.state==='staged'?'staged':'queued',reviewNote:server?.previousReviewNote||saved?.reviewNote||''};});render();
 }
 async function initialize(){try{
  const viewer=await refreshAuth();owner=viewer?.userId;if(!owner){const loginHref=`/${locale}/account/?returnTo=${encodeURIComponent(location.href)}`;$('[data-photo-login]').href=loginHref;$('[data-photo-access-login]').href=loginHref;$('[data-photo-login]').hidden=state.auth==='unavailable';say(state.auth==='unavailable'?copy.authUnavailable:copy.loginFirst,state.auth==='unavailable'?'error':'info');updateButtons();return;}
  const [catalog,types]=await Promise.all([request('/entities'),request('/types')]);entities=catalog.entities;mediaTypes=types.types;for(const type of mediaTypes)$('[data-default="mediaType"]').add(new Option(type.labels?.[locale]||type.labels?.zh||type.id,type.id));const options=$('[data-entity-options]');for(const entity of entities){const label=create('label'),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.value=entity.id;label.append(checkbox,create('span',entity.labels?.[locale]||entity.name));options.append(label);}
  const localDrafts=await listGalleryDrafts(owner).catch(()=>[]),search=new URLSearchParams(location.search),retry=search.get('retry');let id=search.get('batch');let local=id?localDrafts.find(draft=>draft.id===id):!retry&&!search.has('new')?localDrafts.find(draft=>draft.kind==='photos'):null;id||=local?.id;let remote=null;
  if(retry&&!id){let retryDraft=search.get('retryDraft');if(!retryDraft||!/^[-\w]{1,100}$/.test(retryDraft)){retryDraft=crypto.randomUUID();const url=new URL(location.href);url.searchParams.set('retryDraft',retryDraft);history.replaceState(null,'',url);}const resumed=await request('/batches/'+encodeURIComponent(retry)+'/retry','POST',{id:retryDraft});id=resumed.batch.id;const url=new URL(location.href);url.searchParams.delete('retry');url.searchParams.delete('retryDraft');url.searchParams.set('batch',id);history.replaceState(null,'',url);}
  if(id){remote=await request('/batches/'+encodeURIComponent(id)).catch(error=>{if(local&&(error.status===404||!error.status))return null;throw error;});batch=remote?.batch;if(batch&&batch.kind!=='photos')throw Error(copy.wrongBatch);if(batch&&batch.status!=='draft'){say(copy.review);$('[data-photo-receipt]').href=`/${locale}/account/creator/?recordType=gallery&record=${encodeURIComponent(batch.id)}`;$('[data-photo-receipt]').hidden=false;disposed=true;updateButtons();return;}}
  restoreFiles(local?.manifest||remote?.batch.manifest,local,remote);setupDraft(local||{id:id||crypto.randomUUID(),version:batch?.version});say(retry?copy.retryReady:copy.readyStatus);if(files.some(file=>file.state==='queued'))void stagePending();
 }catch(error){say(error.message,'error');}updateButtons();}
 $('[data-photo-access-retry]').onclick=async()=>{const button=$('[data-photo-access-retry]');button.disabled=true;const viewer=await refreshAuth(true);if(viewer){location.reload();return;}say(state.auth==='unavailable'?copy.authUnavailable:copy.loginFirst,state.auth==='unavailable'?'error':'info');$('[data-photo-login]').hidden=state.auth==='unavailable';updateButtons();button.disabled=false;};
 window.addEventListener('kamitsubaki-account-state',()=>{if(owner&&state.viewer?.userId!==owner){void draftController?.persist().catch(()=>{});draftController?.close();disposed=true;uploadController.abort();files.forEach(file=>{if(file.url?.startsWith('blob:'))URL.revokeObjectURL(file.url);});files=[];root.querySelectorAll('[data-default]').forEach(input=>input.value='');root.querySelectorAll('input[type=checkbox]').forEach(input=>input.checked=false);const inspector=$('[data-photo-inspector]');if(inspector?.open)inspector.close();$('[data-photo-inspector-body]')?.replaceChildren();selectedPhoto=null;render();say(copy.accountChanged,'error');}});
 window.addEventListener('online',()=>{if(!disposed&&draftController&&!draftController.conflict){void draftController.sync().catch(()=>{});void stagePending();}});
 window.addEventListener('pagehide',()=>void draftController?.persist().catch(()=>{}));
 window.addEventListener('beforeunload',event=>{if(stageFlight||localFilesUnavailable&&files.some(file=>file.state!=='staged')||draftController?.localState==='saving'||draftController?.localState==='error'){event.preventDefault();event.returnValue='';}});
 updateButtons();void initialize();
}
